name: Archiver

on:
  workflow_dispatch:
    inputs:
      name:
        description: Extension name
        type: choice
        required: true
        options:
          - Wikibase
          - VisualEditor
      ref:
        description: Branch ref
        default: REL1_43
        type: string
        required: true

jobs:
  archive:
    runs-on: ubuntu-latest
    steps:
      - name: Store timestamp
        run: echo "TIMESTAMP=$(date +%s)" >> $GITHUB_ENV

      - name: Set archive name
        run: echo "ARCHIVE_NAME=${{ github.event.inputs.name }}-${{ env.TIMESTAMP }}-${{ inputs.ref }}.tar.gz" >> $GITHUB_ENV

      - name: Check out this repository
        uses: actions/checkout@v3
        with:
          # Requires "Read and write permissions" in Actions > General > Workflow permissions
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Download extension
        run: |
          URL=$(
            curl --max-time 20 --connect-timeout 20 --silent "https://www.mediawiki.org/w/api.php?action=query&format=json&list=extdistbranches&formatversion=2&edbexts=${{ github.event.inputs.name }}" |
            jq ".query.extdistbranches.extensions.${{ github.event.inputs.name }}.${{ inputs.ref }}"
          )
          echo "Downloading $URL"
          echo $URL | xargs curl --max-time 20 --connect-timeout 20 --fail --output ${{ env.ARCHIVE_NAME }}

      - name: Commit and push archive
        uses: EndBug/add-and-commit@v9
        with:
          message: Add ${{ env.ARCHIVE_NAME }}
          default_author: github_actions
          push: true
