name: packager

on:
  workflow_dispatch:
    inputs:
      ref:
        description: Wikibase ref
        default: REL1_38
        type: string
        required: true

env:
  ARCHIVE_NAME: wikibase_${{ inputs.ref }}.tar.gz

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Wikibase
        uses: actions/checkout@v3
        with:
          submodules: true
          repository: wikimedia/mediawiki-extensions-Wikibase
          path: ./repos/Wikibase
          ref: ${{ inputs.ref }}
          # Fetching submodules may fail if "fetch-depth" is too shallow
          fetch-depth: 3

      - name: Remove .git related files
        run: cd ./repos/Wikibase && ( find . -type d -name ".git" && find . -name ".gitignore" && find . -name ".gitmodules" ) | xargs rm -rf

      - name: Check out this repository
        uses: actions/checkout@v3
        with:
          path: ./repos/release
          # Requires "Read and write permissions" in Actions > General > Workflow permissions
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create a Wikibase archive file
        run: cd ./repos && tar -czvf ./release/${{ env.ARCHIVE_NAME }} ./Wikibase

      - name: Commit and push archive
        uses: EndBug/add-and-commit@v9
        with:
          cwd: ./repos/release
          message: Add ${{ env.ARCHIVE_NAME }}
          default_author: github_actions
          push: true
